### ISSUE TITLE
[Crash]: When getting hitted by a crossbow  on a horse, with Appleskin mod.

### ISSUE THREAD

**Issue by HOLYSPAGETI** [Fuzss/leavemybarsalone#3] opened 2023-01-09 16:26 UTC
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

40.1.70

### Notes (Required)

1. Riding a horse
2. Getting hit by a crossbow
3. The game crash
4. When you try to login it crash again, in a loop, making player data cancellation looking like the only way to fix.

### Crash Report (Required)

https://gist.github.com/HOLYSPAGETI/73f40e757b726eb744d8d70a01673008#file-crash-2023-01-09_17-03-33-client-txt

**Comment by Fuzss** [comment] 2023-03-26 19:01
Thanks for the report! Duplicate of #2.

**Closed as completed by Fuzss** 2023-03-26 19:01 UTC
Labels: bug
